### ISSUE TITLE
Distro requirement breaks gem builds

### ISSUE THREAD

**Issue by kylev** [computology/packagecloud-ruby#19]
It looks like the new requirement for a "distro" breaks previously working builds on Travis.

```
Deploying application
Detected supported package: gt_credits-1.4.2.gem
/home/travis/.rvm/gems/ruby-2.2.3/gems/packagecloud-ruby-1.0.5/lib/packagecloud/client.rb:172:in `include?': no implicit conversion of nil into String (TypeError)
	from /home/travis/.rvm/gems/ruby-2.2.3/gems/packagecloud-ruby-1.0.5/lib/packagecloud/client.rb:172:in `block in find_distribution_id'
	from /home/travis/.rvm/gems/ruby-2.2.3/gems/packagecloud-ruby-1.0.5/lib/packagecloud/client.rb:172:in `select'
	from /home/travis/.rvm/gems/ruby-2.2.3/gems/packagecloud-ruby-1.0.5/lib/packagecloud/client.rb:172:in `find_distribution_id'
	from /home/travis/.rvm/gems/ruby-2.2.3/gems/dpl-1.8.26/lib/dpl/provider/packagecloud.rb:32:in `get_distro'
	from /home/travis/.rvm/gems/ruby-2.2.3/gems/dpl-1.8.26/lib/dpl/provider/packagecloud.rb:114:in `block in push_app'
	from /home/travis/.rvm/gems/ruby-2.2.3/gems/dpl-1.8.26/lib/dpl/provider/packagecloud.rb:113:in `each'
	from /home/travis/.rvm/gems/ruby-2.2.3/gems/dpl-1.8.26/lib/dpl/provider/packagecloud.rb:113:in `push_app'
	from /home/travis/.rvm/gems/ruby-2.2.3/gems/dpl-1.8.26/lib/dpl/provider.rb:145:in `block in deploy'
	from /home/travis/.rvm/gems/ruby-2.2.3/gems/dpl-1.8.26/lib/dpl/cli.rb:41:in `fold'
	from /home/travis/.rvm/gems/ruby-2.2.3/gems/dpl-1.8.26/lib/dpl/provider.rb:145:in `deploy'
	from /home/travis/.rvm/gems/ruby-2.2.3/gems/dpl-1.8.26/lib/dpl/cli.rb:32:in `run'
	from /home/travis/.rvm/gems/ruby-2.2.3/gems/dpl-1.8.26/lib/dpl/cli.rb:7:in `run'
	from /home/travis/.rvm/gems/ruby-2.2.3/gems/dpl-1.8.26/bin/dpl:5:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-2.2.3/bin/dpl:23:in `load'
	from /home/travis/.rvm/gems/ruby-2.2.3/bin/dpl:23:in `<main>'
failed to deploy
```

The [PackageCloud documentation](https://packagecloud.io/docs#os_distro_version) still indicates that a distro name (or OS version) is not required for gem publishing.

**Comment by capotej** [comment]
Ah, sorry, it looks like this is indeed a bug in my [latest changes to dpl](https://github.com/travis-ci/dpl/pull/541). Thanks for the report! 

I'll have a fix out shortly, but in the meantime you can use the previous version of dpl in your travis config, like so:

```
deploy:
  provider: packagecloud
  edge:
    source: computology/dpl
    branch: 1.8.25
```

**Comment by capotej** [comment]
The fix is up for review here: https://github.com/travis-ci/dpl/pull/552

But you can use it now by setting the following in your `.travis.yml`

```
deploy:
  provider: packagecloud
  edge:
    source: computology/dpl
    branch: pcloud_gems
```

**Comment by capotej** [comment]
The fix has been merged and deployed to dpl: https://github.com/travis-ci/dpl/issues/551, closing ticket.
