### ISSUE TITLE
package_cloud fails on big file sizes

### ISSUE THREAD

**Issue by tonylambiris** [computology/packagecloud-ruby#20]
```Pushing texlive-2016-17.20160520.el7.csos.src.rpm... /home/tlambiris/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/openssl/buffering.rb:322:in `syswrite': integer 2169000531 too big to convert to `int' (RangeError)
	from /home/tlambiris/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/openssl/buffering.rb:322:in `do_write'
	from /home/tlambiris/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/openssl/buffering.rb:340:in `write'
	from /home/tlambiris/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/net/protocol.rb:211:in `write0'
	from /home/tlambiris/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/net/protocol.rb:185:in `block in write'
	from /home/tlambiris/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/net/protocol.rb:202:in `writing'
	from /home/tlambiris/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/net/protocol.rb:184:in `write'
	from /home/tlambiris/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/net/http/generic_request.rb:188:in `send_request_with_body'
	from /home/tlambiris/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/net/http/generic_request.rb:121:in `exec'
	from /home/tlambiris/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/net/http.rb:1435:in `block in transport_request'
	from /home/tlambiris/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/net/http.rb:1434:in `catch'
	from /home/tlambiris/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/net/http.rb:1434:in `transport_request'
	from /home/tlambiris/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/net/http.rb:1407:in `request'
	from /home/tlambiris/.rvm/gems/ruby-2.3.3/gems/rest-client-1.6.9/lib/restclient/net_http_ext.rb:51:in `request'
	from /home/tlambiris/.rvm/gems/ruby-2.3.3/gems/rest-client-1.6.9/lib/restclient/request.rb:210:in `block in transmit'
	from /home/tlambiris/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/net/http.rb:853:in `start'
	from /home/tlambiris/.rvm/gems/ruby-2.3.3/gems/rest-client-1.6.9/lib/restclient/request.rb:206:in `transmit'
	from /home/tlambiris/.rvm/gems/ruby-2.3.3/gems/rest-client-1.6.9/lib/restclient/request.rb:68:in `execute'
	from /home/tlambiris/.rvm/gems/ruby-2.3.3/gems/rest-client-1.6.9/lib/restclient/request.rb:35:in `execute'
	from /home/tlambiris/.rvm/gems/ruby-2.3.3/gems/package_cloud-0.2.40/lib/package_cloud/repository.rb:52:in `create_package'
	from /home/tlambiris/.rvm/gems/ruby-2.3.3/gems/package_cloud-0.2.40/lib/package_cloud/cli/entry.rb:166:in `create_package_skip_errors'
	from /home/tlambiris/.rvm/gems/ruby-2.3.3/gems/package_cloud-0.2.40/lib/package_cloud/cli/entry.rb:140:in `block (3 levels) in push'
	from /home/tlambiris/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/benchmark.rb:293:in `measure'
	from /home/tlambiris/.rvm/gems/ruby-2.3.3/gems/package_cloud-0.2.40/lib/package_cloud/cli/entry.rb:138:in `block (2 levels) in push'
	from /home/tlambiris/.rvm/gems/ruby-2.3.3/gems/package_cloud-0.2.40/lib/package_cloud/cli/entry.rb:128:in `each'
	from /home/tlambiris/.rvm/gems/ruby-2.3.3/gems/package_cloud-0.2.40/lib/package_cloud/cli/entry.rb:128:in `block in push'
	from /home/tlambiris/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/benchmark.rb:293:in `measure'
	from /home/tlambiris/.rvm/gems/ruby-2.3.3/gems/package_cloud-0.2.40/lib/package_cloud/cli/entry.rb:70:in `push'
	from /home/tlambiris/.rvm/gems/ruby-2.3.3/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /home/tlambiris/.rvm/gems/ruby-2.3.3/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/tlambiris/.rvm/gems/ruby-2.3.3/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /home/tlambiris/.rvm/gems/ruby-2.3.3/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /home/tlambiris/.rvm/gems/ruby-2.3.3/gems/package_cloud-0.2.40/bin/package_cloud:4:in `<top (required)>'
	from /home/tlambiris/.rvm/gems/ruby-2.3.3/bin/package_cloud:22:in `load'
	from /home/tlambiris/.rvm/gems/ruby-2.3.3/bin/package_cloud:22:in `<main>'
	from /home/tlambiris/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `eval'
	from /home/tlambiris/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `<main>'
19:07:09 c1-linuxdev ~/Public/packages/rpms $ ls -lah texlive-2016-17.20160520.el7.csos.src.rpm
-rw-r--r-- 1 tlambiris users 2.1G Jan 27 05:00 texlive-2016-17.20160520.el7.csos.src.rpm```

Fairly self-explanatory, didn't realize how big the file actually was until after it tried to upload the bulk of it first. Would be nice to have a `--size-limit` flag to trigger a message or error if the file size exceeds the what was passed in for an argument.

Thanks!

**Comment by tonylambiris** [comment]
Too soon? Lol.
