### ISSUE TITLE
Missing json requirement

### ISSUE THREAD

**Issue by dennybaa** [computology/packagecloud-ruby#8]
irb(main):001:0> require 'packagecloud'

```
NameError: uninitialized constant JSON
	from /root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/packagecloud-ruby-0.2.22/lib/packagecloud/client.rb:1:in `<top (required)>'
	from /root/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /root/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/packagecloud-ruby-0.2.22/lib/packagecloud.rb:2:in `<top (required)>'
	from /root/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require'
	from /root/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
	from /root/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	from (irb):1
	from /root/.rbenv/versions/2.2.3/bin/irb:11:in `<main>'
```

**Comment by capotej** [comment]
We just released 0.2.23 which should solve this issue: https://rubygems.org/gems/packagecloud-ruby/versions/0.2.23
